### ISSUE TITLE
Getting `ValueError: Mesh boundary crosses itself! Folded element(s)!` for `Irene`

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [oceanmodeling/ondemand-storm-workflow#30]
@SorooshMani-NOAA the workflow failed with the following error message related to mesh. Can you please take a look at this? Thanks
```
Traceback (most recent call last):
  File "/opt/conda/envs/ocsmesh/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/ocsmesh/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scripts/hurricane_mesh.py", line 546, in <module>
    main(args, [hurrmesh_client, subset_client])
  File "/scripts/hurricane_mesh.py", line 97, in main
  File "/opt/conda/envs/ocsmesh/lib/python3.9/site-packages/ocsmesh/utils.py", line 426, in finalize_mesh
    boundary_polys = get_mesh_polygons(mesh)
  File "/opt/conda/envs/ocsmesh/lib/python3.9/site-packages/ocsmesh/utils.py", line 213, in get_mesh_polygons
    lines = get_boundary_segments(target_mesh)
  File "/opt/conda/envs/ocsmesh/lib/python3.9/site-packages/ocsmesh/utils.py", line 186, in get_boundary_segments
    raise ValueError(
ValueError: Mesh boundary crosses itself! Folded element(s)!
ERROR conda.cli.main_run:execute(49): `conda run python -m hurricane_mesh irene 2011 subset_n_combine /lustre/static_data/grid/stofs3d_atl_v2.1_eval.gr3 /lustre/static_data/grid/WNAT_1km.14 /lustre/hurricanes/irene_2011_d2721f99-5e07-4b24-91b5-5808692ffbb9/windswath --rasters /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n0.0_s-90.0_w-180.0_e-90.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n0.0_s-90.0_w-90.0_e0.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n0.0_s-90.0_w0.0_e90.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n0.0_s-90.0_w90.0_e180.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n90.0_s0.0_w-180.0_e-90.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n90.0_s0.0_w-90.0_e0.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n90.0_s0.0_w0.0_e90.0.tif /lustre/static_data/dem/gebco/gebco_2021_sub_ice_topo_n90.0_s0.0_w90.0_e180.0.tif --out /lustre/hurricanes/irene_2011_d2721f99-5e07-4b24-91b5-5808692ffbb9/mesh` failed. (See above for error)
```

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA the fix I talked about this morning should take care of this. I'm rebuilding some of the images. I'll let you know once done.

**Comment by FariborzDaneshvar-NOAA** [comment]
> @FariborzDaneshvar-NOAA the fix I talked about this morning should take care of this. I'm rebuilding some of the images. I'll let you know once done.

Thanks, and sorry for the confusion!

**Comment by SorooshMani-NOAA** [comment]
Sorry I forgot to ping you. It's fixed now! Please let me know if you still see any issues.

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA Thanks for fixing this. all good!
