### ISSUE TITLE
`KeyError: 'Author'` from `enhance/native_conda` branch

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [oceanmodeling/ondemand-storm-workflow#53]
The workflow failed after mesh with this error message:
```
Download necessary data...
Traceback (most recent call last): 
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/bin/download_data", line 5, in <module>  
    from stormworkflow.prep.download_data import cli                                                             
  File "/nhc/Fariborz.Daneshvar/sandbox/workflow_native/ondemand-storm-workflow/stormworkflow/prep/download_data.py", line 8, in <module>  
    from pyschism.mesh import Hgrid
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/__init__.py", line 4, in <module>                                                                                               
    from pyschism.stations import Stations                                                                       
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/stations.py", line 12, in <module>                                                                                              
    from pyschism.enums import (                                                                                 
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/enums.py", line 707, in <module> 
    class Sflux1Types(Enum):    
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/enums.py", line 709, in Sflux1Types                                
    from pyschism.forcing import nws                                                                             
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/forcing/__init__.py", line 3, in <module>                                                                                     
    from pyschism.forcing.nws.nws2.gfs import GlobalForecastSystem                                               
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/forcing/nws/__init__.py", line 1, in <module>                                                                                 
    from pyschism.forcing.nws.nws2 import NWS2                                                                   
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/forcing/nws/nws2/__init__.py", line 1, in <module>                                                                            
    from pyschism.forcing.nws.nws2.nws2 import NWS2                                                              
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/forcing/nws/nws2/nws2.py", line 9, in <module>                                                                                
    from pyschism.forcing.nws.nws2.sflux import SfluxDataset                                                     
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/pyschism/forcing/nws/nws2/sflux.py", line 9, in <module>                                                                               
    import cf                                                                                                    
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/cf/__init__.py", line 344, in <module>                                                                                                 
    from .regrid import RegridOperator                                                                           
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/cf/regrid/__init__.py", line 1, in <module>                                                                                            
    from .regrid import regrid                                                                                   
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/cf/regrid/regrid.py", line 18, in <module>                                                                                             
    import esmpy                                                                                                 
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/esmpy/__init__.py", line 106, in <module>                                                                                              
    __author__ = msg["Author"]                                                                                   
  File "/nhc/Fariborz.Daneshvar/miniconda3/envs/stormworkflow/lib/python3.10/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__                                                                              
    raise KeyError(item)                                                                                       
KeyError: 'Author'                                                                                             
None
```

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA suggested checking version of packages. 
```
esmpy                     8.4.2              pyhc1e730c_4    conda-forge 
```
`conda list | grep cf`
```
cf-python                 3.16.1          py310hc57ae4c_0    conda-forge                                       
cfdm                      1.11.1.0        py310hff52083_0    conda-forge                                       
cffi                      1.16.0          py310h2fee648_0    conda-forge                                       
cfgrib                    0.9.13.0           pyhd8ed1ab_0    conda-forge                                       
cfitsio                   4.2.0                hd9d235c_0    conda-forge                                       
cftime                    1.6.4           py310h261611a_0    conda-forge                                       
cfunits                   3.3.7              pyhd8ed1ab_0    conda-forge
```
The only difference with Soroosh's environment was cfgrib `0.9.13.0` (instead of `0.9.12.0`)

**Comment by FariborzDaneshvar-NOAA** [comment]
I changed `cfgrib` version (`conda install "cfgrib=0.9.12.0"`) and re-ran the workflow, but it failed again with the same error!

**Comment by FariborzDaneshvar-NOAA** [comment]
For the record, similar issue:  https://github.com/ESMValGroup/ESMValTool/issues/3208
